In [2]:
import h5py
import numpy as np
import pandas as pd

# Open and inspect the H5 file
h5_path = "/home/shinben0327/3dv/dataset_replay/data/h5/20250922_143954.h5"

with h5py.File(h5_path, 'r') as f:
    print("=" * 60)
    print("H5 File Structure")
    print("=" * 60)
    
    def print_structure(name, obj):
        indent = "  " * name.count('/')
        if isinstance(obj, h5py.Dataset):
            print(f"{indent}{name}: shape={obj.shape}, dtype={obj.dtype}")
        else:
            print(f"{indent}{name}/ (Group)")
    
    f.visititems(print_structure)
    
    print("\n" + "=" * 60)
    print("Camera Intrinsics")
    print("=" * 60)
    if 'observations/images/oakd_front_view/intrinsics' in f:
        intrinsics = f['observations/images/oakd_front_view/intrinsics'][:]
        print("Intrinsic Matrix (K):")
        print(intrinsics.reshape(3, 3))
    
    print("\n" + "=" * 60)
    print("Camera Extrinsics")
    print("=" * 60)
    if 'observations/images/oakd_front_view/extrinsics' in f:
        extrinsics = f['observations/images/oakd_front_view/extrinsics'][:]
        print("Extrinsic Matrix (4x4):")
        print(extrinsics.reshape(4, 4))
    
    print("\n" + "=" * 60)
    print("Dataset Summary")
    print("=" * 60)
    print(f"Total groups/datasets: {len(list(f.keys()))}")
    for key in f.keys():
        if isinstance(f[key], h5py.Dataset):
            print(f"{key}: {f[key].shape}")

H5 File Structure
actions_arm_right: shape=(107, 7), dtype=float64
actions_hand_right: shape=(107, 17), dtype=float64
observations/ (Group)
  observations/images/ (Group)
    observations/images/oakd_front_view/ (Group)
      observations/images/oakd_front_view/color: shape=(107, 270, 480, 3), dtype=uint8
      observations/images/oakd_front_view/extrinsics: shape=(16,), dtype=float32
      observations/images/oakd_front_view/intrinsics: shape=(9,), dtype=float32
    observations/images/oakd_right_wrist_view/ (Group)
      observations/images/oakd_right_wrist_view/color: shape=(107, 270, 480, 3), dtype=uint8
  observations/qpos_arm_right: shape=(107, 7), dtype=float64
  observations/qpos_hand_right: shape=(107, 17), dtype=float64

Camera Intrinsics
Intrinsic Matrix (K):
[[299.23807   0.      244.32437]
 [  0.      299.35458 138.16463]
 [  0.        0.        1.     ]]

Camera Extrinsics
Extrinsic Matrix (4x4):
[[-4.2128158e-04 -9.0987319e-01  4.1488630e-01  8.3224699e-02]
 [-9.9924862e